### ISSUE TITLE
Notifications are send out after editing an existing instance of reengagement

### ISSUE THREAD

**Issue by jbs1** [catalyst/moodle-mod_reengagement#156] opened 2024-06-04 13:26 UTC
Hey,

So i have setup my mod instance to sent out a notification base on a time and activity completion.
So I setup the instance to notifiy on completion and setup the reengagement duration to something like 1 minute.
Then I set the restrict access to a specific time and the respective activity completion. This seems to work fine. So it makes the reengagement activity available when the specificed time is up and the activity completion condition is also met and then it sets the reengagement to complete, after the restrict access conditions are meet, and 1 minute later it sends out the messages..

However this seems to only work when i setup the reengagement the first time. When i tried to change for example the restrict access conditions it will mark all users immediately as complete on saving and send out the notifications regardless of what the restrict access says.

This seems to be kinda weird behaviour.

Repro Steps

- Create reeng instance
- set to notify on complete
- set duration to 1 minute
- set restrict access to some date in the future
- notice, how after saving the activity completion report will not show instance as complete for anybody
- edit something in the reeng instance settings
- notice, after save the activity completion report shows all users as complete regardless of what restrict access conditions say

**Comment by danmarsden** [comment] 2024-06-04 21:42
Thanks - this is basically a duplicate of #52 - if you have internal development capabilities, pull requests are always welcome, alternatively feel free to reach out privately if you would like to fund improvements to the plugin - thanks!

**Closed as completed by danmarsden** 2024-06-04 21:42 UTC
