### ISSUE TITLE
Debug notice on possible performance improvement in participants class when testing on M37

### ISSUE THREAD

**Issue by logan-reynolds** [catalyst/moodle-mod_reengagement#53] opened 2019-05-26 20:22 UTC
In testing the latest version 2019011700 release 3.6.1 from Moodle.org on Moodle 3.7 (Build: 20190520) I'm seeing the following notices with debug enabled, although the plugin does still appear to function - just seeing if it's acceptable to run this version on M37 and if this would cause any problems when running the plugin on that version once it's available to clients:
```
Please do not call get_users_roles() with $checkparentcontexts = true and $userids array not set. This combination causes large Moodle sites with lots of site-wide role assignments to run out of memory.

    line 2812 of /lib/accesslib.php: call to debugging()
    line 250 of /mod/reengagement/classes/table/participants.php: call to get_users_roles()
    line 226 of /mod/reengagement/view.php: call to mod_reengagement\table\participants->__construct()
```

**Comment by danmarsden** [comment] 2019-05-26 21:34
Tihs is a duplicate of #44 which has been fixed in the master branch here - but hasn't been rolled into a release in the plugins db yet.

**Closed by danmarsden** 2019-05-26 21:34 UTC
