### ISSUE TITLE
Help with timed release

### ISSUE THREAD

**Issue by diwuwudi** [catalyst/moodle-mod_reengagement#10] opened 2016-09-28 00:38 UTC
Hi,

I read the documentation about the timed release function [HERE](https://docs.moodle.org/31/en/Reengagement_activity#Timed_release) and I thought I set all the settings correctly but it did not seem to work.

Basically I was trying this out with two testing quizzes: MCQ first and MCQ second. Moodle version is 2.9 and completion tracking is enabled for the course. For testing purposes, I want the MCQ second to be opened 5 minutes after the MCQ first is marked complete. Based on my understanding of the plugin, it can be used as a timer to delay the release of activities. 

When MCQ first is marked complete, the Reengagement activity should be accessible. Since the reengagement activity is hidden from the user, it should act as a timer. After 5 minutes, the reengagement activity is marked complete and the MCQ second should be released. I tested it using a student account (not switching roles). The MCQ first is marked complete but the MCQ second is not released. And as a student, I cannot check whether the reengagement activity is now marked complete.

I have attached the settings page below and hopefully someone could help me figure out what went wrong. Perhaps I did not understand the function of the plugin correctly? Any advice is appreciated.

Thanks for reading my post :)

![1](https://cloud.githubusercontent.com/assets/11310029/18896668/db06171a-8566-11e6-99a9-1ca95fba2bd3.png)

![2](https://cloud.githubusercontent.com/assets/11310029/18896672/e1b3c472-8566-11e6-94f0-fcf4dac42051.png)

**Comment by danmarsden** [comment] 2016-09-28 09:11
Hi there, 

The best place to ask for free "help" or "advice" is the community forums on moodle.org.

Trackers are for reporting bugs or feature requests - closing this one here, as not a bug, but feel free to ask your questions in the "general plugins" forum on moodle.org

If you are looking for commercial level support feel free to get back in touch - more information on our services is available here:
https://www.catalyst.net.nz/products/elearning

**Closed by danmarsden** 2016-09-28 09:11 UTC
