### ISSUE TITLE
Restricted activity not shown after reengagement completed

### ISSUE THREAD

**Issue by hosnas** [catalyst/moodle-mod_reengagement#32] opened 2017-12-03 09:33 UTC
Using the latest plugin and moodle, Here is the scenario to reproduce the issue.
1- creating a reengagement activity of five minutes, without any restriction, named r1.
2- creating an assignment activity, restricted to r1 completion, and hidden if user does not meet requirement.

I log in as a test user and enroll it to the course. I wait for five minutes but nothing happens.

![screenshot from 2017-12-03 19-25-21](https://user-images.githubusercontent.com/26921196/33527092-e2f2f84c-d85f-11e7-9574-a4c3343ea881.png)

In this example, **wait** activity is set to be 5 mins. I waited for 10 mins with no luck.

What could be wrong?

**Comment by hosnas** [comment] 2017-12-03 22:26
I analyzed this issue a little bit more.
As you can see in the following picture, a reengagement activity called wait is set to be completed at 1:54. 
![screenshot from 2017-12-04 01-49-53](https://user-images.githubusercontent.com/26921196/33530501-e2bdbd36-d895-11e7-9e2d-c012a45a23e9.png)

However after 1:54, as you can see, the activity is not completed yet.

![screenshot from 2017-12-04 01-55-38](https://user-images.githubusercontent.com/26921196/33530552-5b25bf44-d896-11e7-8ead-b7a60594a2da.png)

**Comment by danmarsden** [comment] 2017-12-03 23:16
Re-engagment relies on your cron process running correctly. The reengagement cron task is also set to only run once every 5 minutes. If you want it to complete faster than that you could adjust the timing of the task under admin > server > scheduled tasks - that page will also show you when the reengagement cron was last run.

**Comment by hosnas** [comment] 2017-12-04 07:40
@danmarsden  thank you for your reply. 
Yes I have already seen the cron page and made it to run every 1 minutes. It seems cron is working correctly. And my problem isn't that the restricted activity is not available as soon as 5 minutes pass. The problem is it wont be available at all.

**Comment by danmarsden** [comment] 2017-12-14 19:43
not sure sorry - you could try asking for further help in the community forums - all I can suggest is to make sure your cron is running correctly and isn't being blocked by some other broken process.

**Comment by danmarsden** [comment] 2018-02-18 21:24
closing as I cannot reproduce and no further information has been provided.

**Closed by danmarsden** 2018-02-18 21:24 UTC
